### ISSUE TITLE
exit message on stdout

### ISSUE THREAD

**Issue by bAndie91** [domo141/keept#1]
hi Tomi,
let me express my appreciation, `keept` is very useful!

i'm concerning about one detail, why exit message is being put on stdout and not stderr ([here](https://github.com/domo141/keept/blob/edcb488813f3cc43d7b65fa80596ad287a877c91/keept.c#L6)), or directly to `/dev/tty`? or are not fd 1 and 2  stdout and stderr here respectively?

thank you.

**Comment by domo141** [comment]
Hi Andreas,

Great that you find keept useful =D

cannot recall exact reason why stdout (fd 1) is used as fd for exit message (e.g. [keept: exit 1])
it could (have) be(en) stderr (fd 2) also.
in comparison: script(1) prints its exit message to stdout (fd 1)
zsh, when setopt printexitvalue is in effect, prints exit message to stderr (fd 2)

/dev/tty it cannot be -- one could run the "client" program of keept from process which does not have controlling tty.

do you have specific reason why stderr would be better than stdout ?

**Comment by bAndie91** [comment]
i'm taking the kind-of unix principle which says, the valuable output - which is a potentional subject of pipelineing, parsing - should go to stdout, and the error to stderr and IMO logs, diagnostic messages, terminal control escape sequences also can not fit to stdout, so they should go to stderr too as there is not more std channel lert.
exit message is a diagnostic output IMO, that's why I'd rather put it on stderr.

i confirm script(1) writes to stdout, and i consider it less professional. because using script, it's quite a use-case to run a pipeline but recording only the left-most command's output like `script -c "ls -l" ls.out | grep something`. in this case progress messages also go through the pipe, which is unwanted.

i admit, `keept` is a bit different, because using it, you probably want to run something in the background, and when you have a pipeline with only 1 step in the background and the other one (or more) in the foreground then practically it's still in the foreground. so put the whole pipeline inside keept and our issue on stdout/err is no more.
but. I find it also a completely valid use-case to run a part of a pipeline in keept, not to send it to the background, but to share. i mean to let yourself inspect the process separately, while still processing/parsing it's output by the pipeline.

**Comment by domo141** [comment]
pushed change to write exitmsgs to stderr. thanks!
